# Generated by Django 4.0.3 on 2022-05-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0002_newcar_usedcar_delete_newcars'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandLogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(default='image/default car.png', upload_to='photos', verbose_name='Logo 1')),
                ('image2', models.ImageField(default='image/default car.png', upload_to='photos', verbose_name='Logo 2')),
                ('image3', models.ImageField(default='image/default car.png', upload_to='photos', verbose_name='Logo 3')),
                ('image4', models.ImageField(default='image/default car.png', upload_to='photos', verbose_name='Logo 4')),
                ('image5', models.ImageField(default='image/default car.png', upload_to='photos', verbose_name='Logo 5')),
                ('image6', models.ImageField(default='image/default car.png', upload_to='photos', verbose_name='Logo 6')),
            ],
        ),
        migrations.AlterField(
            model_name='newcar',
            name='ad_title',
            field=models.CharField(max_length=20, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='usedcar',
            name='ad_title',
            field=models.CharField(max_length=20, unique=True, verbose_name='Title'),
        ),
    ]
