# Generated by Django 4.0.3 on 2022-05-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0003_brandlogos_alter_newcar_ad_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandlogos',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='brandlogos',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='brandlogos',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='brandlogos',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='brandlogos',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='brandlogos',
            name='image6',
        ),
        migrations.AddField(
            model_name='brandlogos',
            name='image',
            field=models.ImageField(default='image/default car.png', upload_to='photos', verbose_name='Logo'),
        ),
    ]
