# Generated by Django 4.0.3 on 2022-05-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0004_remove_brandlogos_image1_remove_brandlogos_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandlogos',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='website'),
        ),
    ]
